services:
  - type: web
    name: nima-ai-marketing-api
    env: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 75
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: PORT
        fromService:
          type: web
          name: nima-ai-marketing-api
          property: port
    healthCheckPath: /health
    plan: starter  # یا free برای تست

